name: Build and Release Checkmol

on:
  push:
    tags:
      - "v*.*.*" # Triggers on tags like v1.0.0

jobs:
  build:
    name: Build and Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            artifact_name: checkmol-x86_64-linux
            binary_name: checkmol
          - os: windows-latest
            artifact_name: checkmol-x86_64-windows.exe
            binary_name: checkmol.exe
          - os: macos-latest
            artifact_name: checkmol-aarch64-apple-darwin
            binary_name: checkmol
          - os: macos-13
            artifact_name: checkmol-x86_64-apple-darwin
            binary_name: checkmol

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FPC
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y fpc
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install fpc
          fi

      - name: Install Free Pascal Compiler on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install freepascal -y
          echo "C:\tools\freepascal\bin\i386-win32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile checkmol.pas
        run: fpc checkmol.pas -S2 -O3 -Op3

      - name: Rename binary
        run: mv checkmol${{ matrix.os == 'windows-latest' && '.exe' || '' }} ${{ matrix.artifact_name }}
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
